spring.application.name=assessment2
spring.application.name=security1
spring.datasource.url= jdbc:postgresql://localhost:5432/SpringBoot
spring.datasource.username=postgres
spring.datasource.password=Akram@1209

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
